name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JavaScript script
        run: node script.js
        env:
          MY_SECRET: ${{ secrets.mySecret }}
